#!/usr/bin/env python3
"""Compute QERS scores for Scenario 1 configurations.

This script is aligned to the QERS paper notes recorded in:
- data/analysis/qers_paper_notes.md

Inputs:
- data/analysis/s1_kpi_table.csv (generated by tools/analyze_campaign.py)

Outputs:
- data/analysis/qers_weights.md
- data/analysis/qers_fusion_scores.csv
- data/analysis/qers_fusion_scores.md

No third-party dependencies.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable


MS = 100.0


VARIANT_RE = re.compile(r"\b(512|768|1024)\b")


def parse_float(value: str | None) -> float | None:
    if value is None:
        return None
    s = value.strip()
    if s == "":
        return None
    try:
        return float(s)
    except ValueError:
        return None


def clamp(x: float, lo: float, hi: float) -> float:
    return lo if x < lo else hi if x > hi else x


def minmax_norm(x: float | None, xmin: float | None, xmax: float | None, ms: float = MS) -> float:
    if x is None or xmin is None or xmax is None:
        return 0.0
    if xmax <= xmin:
        return 0.0
    v = ms * (x - xmin) / (xmax - xmin)
    return clamp(v, 0.0, ms)


def bounds(values: Iterable[float | None]) -> tuple[float | None, float | None]:
    vals = [v for v in values if v is not None and not (math.isnan(v) or math.isinf(v))]
    if not vals:
        return None, None
    return min(vals), max(vals)


def write_csv(path: Path, fieldnames: list[str], rows: list[dict[str, object]]):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow(row)


def write_md_table(path: Path, fieldnames: list[str], rows: list[dict[str, object]]):
    def cell(row: dict[str, object], key: str) -> str:
        v = row.get(key, "")
        if v is None:
            return ""
        return str(v)

    widths = {h: len(h) for h in fieldnames}
    for row in rows:
        for h in fieldnames:
            widths[h] = max(widths[h], len(cell(row, h)))

    header_line = "| " + " | ".join(h.ljust(widths[h]) for h in fieldnames) + " |"
    sep_line = "| " + " | ".join("-" * widths[h] for h in fieldnames) + " |"
    data_lines = [
        "| " + " | ".join(cell(row, h).ljust(widths[h]) for h in fieldnames) + " |" for row in rows
    ]

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join([header_line, sep_line] + data_lines) + "\n", encoding="utf-8")


def pr_level_from_variant(variant: str) -> float:
    """Map ML-KEM variant to an ordinal 'proven resistance' level.

    Default mapping uses NIST security category: 1 (512), 3 (768), 5 (1024).
    """

    m = VARIANT_RE.search(variant)
    if not m:
        return 0.0
    size = int(m.group(1))
    if size == 512:
        return 1.0
    if size == 768:
        return 3.0
    if size == 1024:
        return 5.0
    return 0.0


@dataclass(frozen=True)
class AhpResult:
    weights: list[float]
    lambda_max: float
    ci: float
    cr: float


RI_TABLE: dict[int, float] = {
    1: 0.00,
    2: 0.00,
    3: 0.58,
    4: 0.90,
    5: 1.12,
    6: 1.24,
    7: 1.32,
    8: 1.41,
    9: 1.45,
    10: 1.49,
}


def ahp_geometric_mean(matrix: list[list[float]]) -> AhpResult:
    n = len(matrix)
    if n == 0 or any(len(row) != n for row in matrix):
        raise ValueError("AHP matrix must be square")

    # Row geometric means
    gms: list[float] = []
    for i in range(n):
        prod = 1.0
        for j in range(n):
            prod *= float(matrix[i][j])
        gms.append(prod ** (1.0 / n))

    total = sum(gms)
    if total <= 0:
        raise ValueError("Invalid AHP matrix (non-positive geometric mean sum)")

    w = [gm / total for gm in gms]

    # Estimate lambda_max
    Aw = []
    for i in range(n):
        s = 0.0
        for j in range(n):
            s += float(matrix[i][j]) * w[j]
        Aw.append(s)

    lam = 0.0
    for i in range(n):
        lam += (Aw[i] / w[i]) if w[i] else 0.0
    lambda_max = lam / n if n else 0.0

    ci = (lambda_max - n) / (n - 1) if n >= 3 else 0.0
    ri = RI_TABLE.get(n, 1.49)
    cr = (ci / ri) if ri else 0.0

    return AhpResult(weights=w, lambda_max=lambda_max, ci=ci, cr=cr)


def build_pairwise_matrix(criteria: list[str], a_over_b: dict[tuple[str, str], float]) -> list[list[float]]:
    """Build an AHP pairwise matrix from sparse comparisons.

    a_over_b[(a,b)] means 'a is X times more important than b'.
    """

    idx = {c: i for i, c in enumerate(criteria)}
    n = len(criteria)
    m = [[1.0 for _ in range(n)] for _ in range(n)]
    for (a, b), v in a_over_b.items():
        if a not in idx or b not in idx:
            raise ValueError(f"Unknown criterion in pairwise: {(a, b)}")
        i = idx[a]
        j = idx[b]
        if v <= 0:
            raise ValueError("Pairwise value must be > 0")
        m[i][j] = float(v)
        m[j][i] = 1.0 / float(v)
    return m


def fmt(x: float | None, nd: int = 3) -> str:
    if x is None:
        return ""
    if math.isnan(x) or math.isinf(x):
        return ""
    return f"{x:.{nd}f}"


def load_kpi_rows(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)
        return [dict(row) for row in reader]


def main():
    parser = argparse.ArgumentParser(description="Compute QERS (Fusion) for Scenario 1 configurations")
    parser.add_argument("--kpi", default="data/analysis/s1_kpi_table.csv", help="Input KPI CSV")
    parser.add_argument("--out-dir", default="data/analysis", help="Output directory")
    parser.add_argument(
        "--normalize-within-mode",
        action="store_true",
        help="Use per-mode min/max bounds for normalization (recommended for mode-specific ranking).",
    )
    parser.add_argument(
        "--mode",
        choices=["session", "reconn", "all"],
        default="all",
        help="Filter alternatives by mode before normalization. Use 'all' to include both modes.",
    )
    parser.add_argument(
        "--weights-json",
        default=None,
        help="Load weights from tools/derive_weights.py output (weights_summary.json).",
    )
    # Optional overrides (what-if analysis)
    parser.add_argument("--alpha", type=float, default=None, help="Override Perf weight in Fusion (0..1)")
    parser.add_argument("--beta", type=float, default=None, help="Override Sec weight in Fusion (0..1); if None, set to 1-alpha")
    parser.add_argument(
        "--w-perf",
        default=None,
        help="Override performance sub-weights as 'L=0.45,E=0.35,C=0.10,J=0.05,Ploss=0.05'",
    )
    parser.add_argument(
        "--w-sec",
        default=None,
        help="Override security sub-weights as 'Pr=0.70,K=0.10,R=0.10,Co=0.10'",
    )
    parser.add_argument(
        "--k-orientation",
        choices=["benefit", "cost"],
        default="cost",
        help="Treat K (key/payload bytes) as benefit or cost for S term (default: cost)",
    )
    parser.add_argument(
        "--co-orientation",
        choices=["benefit", "cost"],
        default="cost",
        help="Treat Co (overhead bytes) as benefit or cost for S term (default: cost)",
    )
    args = parser.parse_args()

    kpi_path = Path(args.kpi)
    out_dir = Path(args.out_dir)

    rows = load_kpi_rows(kpi_path)
    if not rows:
        raise SystemExit(f"No rows found in KPI file: {kpi_path}")

    # Optional pre-filter by mode
    if args.mode != "all":
        mode_key = args.mode.strip()
        rows = [r for r in rows if (r.get("mode") or "").strip() == mode_key]
        if not rows:
            raise SystemExit(f"No rows found for mode='{mode_key}' in KPI file: {kpi_path}")

    # --- AHP default weighting (can be revised later) ---
    perf_criteria = ["L", "J", "Ploss", "E", "C"]
    perf_pairwise = {
        ("L", "J"): 3.0,
        ("L", "Ploss"): 2.0,
        ("L", "E"): 2.0,
        ("L", "C"): 5.0,
        ("Ploss", "J"): 3.0,
        ("Ploss", "E"): 3.0,
        ("Ploss", "C"): 5.0,
        ("E", "J"): 2.0,
        ("E", "C"): 3.0,
        ("J", "C"): 2.0,
    }
    perf_matrix = build_pairwise_matrix(perf_criteria, perf_pairwise)
    perf_ahp = ahp_geometric_mean(perf_matrix)
    w_perf = {c: perf_ahp.weights[i] for i, c in enumerate(perf_criteria)}

    sec_criteria = ["Pr", "K", "R", "Co"]
    sec_pairwise = {
        ("Pr", "K"): 5.0,
        ("Pr", "R"): 7.0,
        ("Pr", "Co"): 9.0,
        ("K", "R"): 3.0,
        ("K", "Co"): 5.0,
        ("R", "Co"): 3.0,
    }
    sec_matrix = build_pairwise_matrix(sec_criteria, sec_pairwise)
    sec_ahp = ahp_geometric_mean(sec_matrix)
    w_sec = {c: sec_ahp.weights[i] for i, c in enumerate(sec_criteria)}

    # Top-level Fusion coefficients alpha/beta (performance vs security)
    top_criteria = ["Perf", "Sec"]
    top_pairwise = {("Perf", "Sec"): 1.5}  # target ~ P=0.6, S=0.4
    top_matrix = build_pairwise_matrix(top_criteria, top_pairwise)
    top_ahp = ahp_geometric_mean(top_matrix)
    alpha = top_ahp.weights[0]
    beta = top_ahp.weights[1]

    weights_json = None

    def normalize_weights_map(raw: dict[str, object] | None, keys: list[str]) -> dict[str, float] | None:
        if not isinstance(raw, dict):
            return None
        out: dict[str, float] = {}
        for k in keys:
            v = raw.get(k)
            if v is None:
                return None
            try:
                out[k] = float(v)
            except (TypeError, ValueError):
                return None
            out[k] = max(0.0, out[k])
        ssum = sum(out.values())
        if ssum <= 0:
            return None
        return {k: out[k] / ssum for k in keys}

    def load_weights_json(path_str: str | None):
        if not path_str:
            return None
        path = Path(path_str)
        if not path.is_file():
            return None
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except Exception:
            return None

        perf = normalize_weights_map(data.get("perf_final"), perf_criteria)
        sec = normalize_weights_map(data.get("sec_final"), sec_criteria)

        macro = normalize_weights_map(data.get("macro_weights_suggested"), ["P", "S"])
        if macro is None:
            macro_disp = data.get("macro_dispersion")
            if isinstance(macro_disp, dict):
                macro = normalize_weights_map(
                    {
                        "P": macro_disp.get("P_weight_suggested"),
                        "S": macro_disp.get("S_weight_suggested"),
                    },
                    ["P", "S"],
                )

        return {"perf": perf, "sec": sec, "macro": macro, "path": path}

    weights_json = load_weights_json(args.weights_json)
    if weights_json:
        if weights_json.get("perf"):
            w_perf = weights_json["perf"]
            perf_ahp = AhpResult(weights=[w_perf[c] for c in perf_criteria], lambda_max=0.0, ci=0.0, cr=0.0)
        if weights_json.get("sec"):
            w_sec = weights_json["sec"]
            sec_ahp = AhpResult(weights=[w_sec[c] for c in sec_criteria], lambda_max=0.0, ci=0.0, cr=0.0)
        if weights_json.get("macro"):
            alpha = weights_json["macro"].get("P", alpha)
            beta = weights_json["macro"].get("S", beta)

    # Parse manual overrides if provided
    def parse_weights_arg(s: str | None, keys: list[str]) -> dict[str, float] | None:
        if not s:
            return None
        out: dict[str, float] = {k: 0.0 for k in keys}
        try:
            parts = [p for p in s.split(",") if p]
            for p in parts:
                k, v = p.split("=")
                k = k.strip()
                v = float(v.strip())
                if k in out:
                    out[k] = v
        except Exception:
            return None
        # renormalize
        ssum = sum(max(0.0, v) for v in out.values())
        if ssum > 0:
            out = {k: max(0.0, v) / ssum for k, v in out.items()}
        return out

    w_perf_override = parse_weights_arg(args.w_perf, perf_criteria)
    if w_perf_override:
        w_perf = w_perf_override
        perf_ahp = AhpResult(weights=[w_perf[c] for c in perf_criteria], lambda_max=0.0, ci=0.0, cr=0.0)

    w_sec_override = parse_weights_arg(args.w_sec, sec_criteria)
    if w_sec_override:
        w_sec = w_sec_override
        sec_ahp = AhpResult(weights=[w_sec[c] for c in sec_criteria], lambda_max=0.0, ci=0.0, cr=0.0)

    if args.alpha is not None:
        a = max(0.0, min(1.0, float(args.alpha)))
        b = 1.0 - a if args.beta is None else max(0.0, min(1.0, float(args.beta)))
        ssum = a + b
        if ssum > 0:
            alpha = a / ssum
            beta = b / ssum

    # --- Collect raw metrics per config ---
    def raw_from_row(row: dict[str, str]) -> dict[str, float | None]:
        total_latency = parse_float(row.get("total_latency_us_p50"))
        jitter = parse_float(row.get("jitter_us_p50"))
        ploss = parse_float(row.get("packet_loss_rate"))
        total_energy = parse_float(row.get("total_energy_uj_p50"))
        cpu_util = parse_float(row.get("cpu_util_percent_p50"))
        rssi = parse_float(row.get("rssi_dbm_p50"))
        pub_b = parse_float(row.get("pub_bytes_p50"))
        ct_b = parse_float(row.get("ct_bytes_p50"))
        overhead_b = parse_float(row.get("overhead_bytes_p50"))

        k_bytes = (pub_b + ct_b) if pub_b is not None and ct_b is not None else None
        pr_level = pr_level_from_variant(row.get("variant", ""))

        return {
            "L": total_latency,
            "J": jitter,
            "Ploss": ploss,
            "E": total_energy,
            "C": cpu_util,
            "R": rssi,
            "K": k_bytes,
            "Co": overhead_b,
            "Pr": pr_level,
        }

    # Compute bounds either globally or per mode.
    if args.normalize_within_mode:
        mode_keys = sorted({(r.get("mode") or "").strip() for r in rows})
        mode_bounds: dict[str, dict[str, tuple[float | None, float | None]]] = {}
        for mode in mode_keys:
            mode_rows = [r for r in rows if (r.get("mode") or "").strip() == mode]
            raw_list = [raw_from_row(r) for r in mode_rows]
            b: dict[str, tuple[float | None, float | None]] = {}
            for k in ("L", "J", "Ploss", "E", "C", "R", "K", "Co", "Pr"):
                b[k] = bounds(raw[k] for raw in raw_list)
            mode_bounds[mode] = b
        global_bounds = None
    else:
        raw_list = [raw_from_row(r) for r in rows]
        global_bounds = {k: bounds(raw[k] for raw in raw_list) for k in ("L", "J", "Ploss", "E", "C", "R", "K", "Co", "Pr")}
        mode_bounds = {}

    out_rows: list[dict[str, object]] = []
    for row in rows:
        variant = (row.get("variant") or "").strip()
        pie = (row.get("pie") or "").strip()
        mode = (row.get("mode") or "").strip()

        raw = raw_from_row(row)

        b = global_bounds if global_bounds is not None else mode_bounds.get(mode, {})

        norms = {
            k: minmax_norm(raw[k], *(b.get(k, (None, None))))
            for k in ("L", "J", "Ploss", "E", "C", "R", "K", "Co", "Pr")
        }
        # Apply orientation overrides for K and Co if requested, guard zero-range
        if args.k_orientation == "cost":
            k_lo, k_hi = b.get("K", (None, None))
            if k_lo is not None and k_hi is not None and k_hi > k_lo:
                norms["K"] = MS - norms.get("K", 0.0)
            else:
                norms["K"] = 0.0
        if args.co_orientation == "cost":
            co_lo, co_hi = b.get("Co", (None, None))
            if co_lo is not None and co_hi is not None and co_hi > co_lo:
                norms["Co"] = MS - norms.get("Co", 0.0)
            else:
                norms["Co"] = 0.0

        P = (
            w_perf["L"] * norms["L"]
            + w_perf["J"] * norms["J"]
            + w_perf["Ploss"] * norms["Ploss"]
            + w_perf["E"] * norms["E"]
            + w_perf["C"] * norms["C"]
        )

        S = (
            w_sec["Pr"] * norms["Pr"]
            + w_sec["K"] * norms["K"]
            + w_sec["R"] * norms["R"]
            + w_sec["Co"] * norms["Co"]
        )

        q_fusion = alpha * (MS - P) + beta * S

        out_rows.append(
            {
                "variant": variant,
                "pie": pie,
                "mode": mode,
                "L_us": fmt(raw["L"], 2),
                "E_uj": fmt(raw["E"], 2),
                "J_us": fmt(raw["J"], 2),
                "Ploss_rate": fmt(raw["Ploss"], 4),
                "C_cpu_util_pct": fmt(raw["C"], 2),
                "R_rssi_dbm": fmt(raw["R"], 1),
                "K_bytes": fmt(raw["K"], 0),
                "Co_bytes": fmt(raw["Co"], 0),
                "Pr_level": fmt(raw["Pr"], 0),
                "P_penalty": fmt(P, 3),
                "S_security": fmt(S, 3),
                "QERS_fusion": fmt(q_fusion, 3),
            }
        )

    # Rank (descending by QERS)
    out_rows_sorted = sorted(out_rows, key=lambda r: float(r.get("QERS_fusion") or 0.0), reverse=True)
    for i, r in enumerate(out_rows_sorted, start=1):
        r["rank_global"] = i

    # Also rank within each mode
    by_mode: dict[str, list[dict[str, object]]] = {}
    for r in out_rows_sorted:
        by_mode.setdefault(str(r.get("mode") or ""), []).append(r)
    for mode, items in by_mode.items():
        items_sorted = sorted(items, key=lambda r: float(r.get("QERS_fusion") or 0.0), reverse=True)
        for i, r in enumerate(items_sorted, start=1):
            r[f"rank_{mode}"] = i

    # Persist weights
    weights_lines = []
    weights_lines.append("# QERS weights (AHP default)\n")
    if weights_json and weights_json.get("path"):
        weights_lines.append(f"- loaded from: {weights_json['path']}\n\n")
    weights_lines.append("## Fusion coefficients\n")
    weights_lines.append(f"- alpha (Perf) = {fmt(alpha, 3)}\n")
    weights_lines.append(f"- beta  (Sec)  = {fmt(beta, 3)}\n")
    weights_lines.append(f"- K orientation = {args.k_orientation}\n")
    weights_lines.append(f"- Co orientation = {args.co_orientation}\n")
    weights_lines.append("\n## Performance weights (L, J, Ploss, E, C)\n")
    for c in perf_criteria:
        weights_lines.append(f"- {c}: {fmt(w_perf[c], 3)}\n")
    weights_lines.append(f"- CR(perf) = {fmt(perf_ahp.cr, 3)}\n")
    weights_lines.append("\n## Security weights (Pr, K, R, Co)\n")
    for c in sec_criteria:
        weights_lines.append(f"- {c}: {fmt(w_sec[c], 3)}\n")
    weights_lines.append(f"- CR(sec) = {fmt(sec_ahp.cr, 3)}\n")

    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "qers_weights.md").write_text("".join(weights_lines), encoding="utf-8")

    fields = [
        "rank_global",
        "variant",
        "pie",
        "mode",
        "QERS_fusion",
        "P_penalty",
        "S_security",
        "L_us",
        "E_uj",
        "J_us",
        "Ploss_rate",
        "C_cpu_util_pct",
        "R_rssi_dbm",
        "K_bytes",
        "Co_bytes",
        "Pr_level",
        "rank_session",
        "rank_reconn",
    ]

    write_csv(out_dir / "qers_fusion_scores.csv", fields, out_rows_sorted)
    write_md_table(out_dir / "qers_fusion_scores.md", fields, out_rows_sorted)

    print(f"Wrote QERS outputs to: {out_dir}")


if __name__ == "__main__":
    main()
